### ISSUE TITLE
Warning on Lapin.Connection.consume/3 on Elixir 1.17.2 Erlang 27.0.1

### ISSUE THREAD

**Issue by samirbilalmemon** [lucacorti/lapin#178]
Compiling leads to no warnings using the workaround for OTP 27 but handling a message while the app is running leads to the following warning

```
warning: using module.function() notation (with parentheses) to fetch map field :payload is deprecated, you must remove the parentheses: map.field
  (myapp 0.1.0) lib/myapp/worker.ex:7: Myapp.Worker.handle_deliver/2
  (lapin 1.0.7) lib/lapin/connection.ex:326: Lapin.Connection.consume/3
```

**Comment by lucacorti** [comment]
I think the warning is about `lib/myapp/worker.ex:7`, not the connection.
